[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

# In production on Netlify, if BACKEND_URL environment variable is set in Netlify settings
[[redirects]]
  from = "/api/*"
  to = ":BACKEND_URL/api/:splat"
  status = 200
  force = false

# Single Page Application Frontend Client Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
